#!/bin/bash

# This script is run on the local host system, NOT in the docker container.
set -e

# make it work on both mac and unix
function mktmpfile() {
  mktemp 2>/dev/null || mktemp -t 'hbuild'
}

tar c --exclude .build/app --exclude .git . | docker run -i jesperfj/heroku-nodejs-builder:latest /buildpack/bin/pipe-compile | {
  while read line; do
    if [ "$line" = "@begin_tar" ]; then
      tarball=$(mktmpfile)
      cat - > $tarball
      rm -rf .build
      mkdir .build
      tar xf $tarball -C .build 
      rm $tarball

      echo "app  : .build/app"
      echo "cache: .build/cache"

    else
      echo $line
    fi
  done
}
